# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-18 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20170415_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Book')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Post')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='post',
            field=models.ManyToManyField(through='django_app.BookContent', to='django_app.Post'),
        ),
    ]
