# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20170419_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
