# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-22 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_requeststat'),
    ]

    operations = [
        migrations.AddField(
            model_name='requeststat',
            name='is_new',
            field=models.BooleanField(default=datetime.datetime(2017, 4, 22, 20, 33, 50, 785000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
